pipeline:
  identifier: Build_quantum_bank_1731005954573
  name: Build quantum-bank
  orgIdentifier: sandbox
  projectIdentifier: Femi_Sandbox
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: femigithub
        repoName: quantum-bank
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - parallel:
                  - step:
                      type: Owasp
                      name: Owasp_1
                      identifier: Owasp_1
                      spec:
                        target:
                          detection: auto
                          type: repository
                        advanced:
                          log:
                            level: info
                          args: {}
                        mode: orchestration
                        config: default
                  - step:
                      type: OsvScanner
                      name: OsvScanner_1
                      identifier: OsvScanner_1
                      spec:
                        target:
                          detection: auto
                          type: repository
                        advanced:
                          log:
                            level: info
                          args: {}
                        mode: orchestration
                        config: default
              - step:
                  type: RunTests
                  name: RunTests_1
                  identifier: RunTests_1
                  spec:
                    language: Python
                    buildTool: Pytest
                    args: ./test/*.py --junitxml=out_report.xml
                    runOnlySelectedTests: true
                    preCommand: pip install -r requirements.txt
                    enableTestSplitting: false
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: femidockerhub
                    repo: mar4r8kfemi/quantum-bank-backend
                    tags:
                      - <+pipeline.sequenceId>
                    caching: true
                    dockerfile: ./Dockerfile
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
